### ISSUE TITLE
Customizably importing CSS from node_modules by passing props

### ISSUE THREAD

**Issue by egoist** [LightBulb/LightBulb#51]
When we use PostCSS import:

```css
import 'bootstrap/components/button'
```

But I want to pass some props to customize the button:

```css
import button from 'bootstrap/components/button'
button({
   padding: 8px 12px;
})
```

**Comment by egoist** [comment]
This can be a compiler built on the top of PostCSS.

For the source file, we simply write PostCSS-compatible code:

```css
/* this is just `postcss-simple-vars` syntax which is valid */
$padding: 10px 20px;
$color: black:

button {
  padding: $padding;
  color: $color;
}
```

Let's called it `wtfCSS` for a temp use:

```javascript
import wtfCSS from 'wtf-css'
wtfCSS(fs.readFileSync('./hi.css'), opts= {
  padding: '8px 12px'
})
// then the $padding in source CSS file will be override by opts.paading
// finally we use postcss to return the compiled css code based on the last-step result.
```
