### ISSUE TITLE
A PostCSS plugin

### ISSUE THREAD

**Issue by egoist** [LightBulb/LightBulb#53]
Input: 

```css
.box {
  height: 40px;
  line-height: @height;
 .child {
    height: @height;
  }
}
```

Output:

```css
.box {
  height: 40px;
  line-height: 40pxt;
}
.box .child {
  height: 40px;
}
```

Why? I miss [Stylus](https://github.com/stylus/stylus).
