### ISSUE TITLE
本地多 node 版本测试

### ISSUE THREAD

**Issue by egoist** [LightBulb/LightBulb#60]
[trevor](https://github.com/vdemedes/trevor) 是模拟的 travis 测试，然而我不需要和 travis 完全一样，而且我懒得装 docker

直接每次测试的时候用 tj/n 切换就行了，比如叫 `ntest`

一个配置文件:

```yaml
node:
  versions:
    - 0.12.0
    - 4.2.4
    - stable
``` 
package.json

```json
"scripts": {
  "test": "ntest ava"
}
```

然后每次都会用 n 切换 node 版本来执行 ava，成功或失败时恢复到开始的版本。
